version: '3.1'

services:
  db:
    image: postgres:14
    restart: always
    command: postgres -c listen_addresses='*'
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${PG_DB_NAME}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}

  test-db:
    image: postgres:14
    restart: always
    ports:
      - 5433:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${PG_DB_NAME}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}

  redis:
    image: redis
    command: redis-server --loglevel warning
    hostname: redis
    ports:
      - '6379:6379'
    volumes:
      - redisdata:/var/lib/redis/data
volumes:
  pgdata:
  redisdata:
